project:
  type: book
  output-dir: docs

lang: fr

book:
  title: "Book test 3"
  author: "Norah Jones"
  date: "23/08/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
    
  sidebar: 
    style: docked

bibliography: references.bib

format:
  html:
    mainfont: "Computer Modern Serif"
    theme: 
      light: simplex
      dark: solar
  pdf:
    documentclass: scrreprt

editor: visual

